name: Deploy Lambda Function for OpenTelemetry Check

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "gradle"

      - name: Build
        run: |
          ./gradlew build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      # - name: Terraform Init
      #   working-directory: packages/otel-lambda-handler/infrastructure
      #   run: terraform init

      # - name: Terraform Plan
      #   working-directory: packages/otel-lambda-handler/infrastructure
      #   run: terraform plan

      # - name: Terraform Apply
      #   working-directory: packages/otel-lambda-handler/infrastructure
      #   run: terraform apply -auto-approve
